INSERT INTO ACCOUNT (ID, AGE, EMAIL, PASSWORD, ROLE, USERNAME) VALUES (1, 20, 'user@user.com', '$2a$10$BffZFqYNQHljIaNSsPfLs.Zz0t3scOPXsZlHE1l2fjovHUsA2tAXi', 'ROLE_USER', 'user');

-- 2. ROLE_MANAGER 계정 추가
INSERT INTO ACCOUNT (ID, AGE, EMAIL, PASSWORD, ROLE, USERNAME) VALUES (2, 20, 'manager@manager.com', '$2a$10$BffZFqYNQHljIaNSsPfLs.Zz0t3scOPXsZlHE1l2fjovHUsA2tAXi', 'ROLE_MANAGER', 'manager');

-- 3. ROLE_ADMIN 계정 추가
INSERT INTO ACCOUNT (ID, AGE, EMAIL, PASSWORD, ROLE, USERNAME) VALUES (3, 20, 'admin@admin.com', '$2a$10$BffZFqYNQHljIaNSsPfLs.Zz0t3scOPXsZlHE1l2fjovHUsA2tAXi', 'ROLE_ADMIN', 'admin');