INSERT INTO ACCOUNT (ID, AGE, EMAIL, PASSWORD, ROLE, USERNAME) VALUES (100, '20', 'user@user.com', '$2a$10$GjSn2QLOfGlKRnSCU8xdPeT0xscg4UES62Jml5xLCck0rDMwqRjci', 'ROLE_USER', 'user');

-- 2. ROLE_MANAGER 계정 추가
INSERT INTO ACCOUNT (ID, AGE, EMAIL, PASSWORD, ROLE, USERNAME) VALUES (101, '20', 'manager@manager.com', '$2a$10$GjSn2QLOfGlKRnSCU8xdPeT0xscg4UES62Jml5xLCck0rDMwqRjci', 'ROLE_MANAGER', 'manager');

-- 3. ROLE_ADMIN 계정 추가
INSERT INTO ACCOUNT (ID, AGE, EMAIL, PASSWORD, ROLE, USERNAME) VALUES (102, '20', 'admin@admin.com', '$2a$10$GjSn2QLOfGlKRnSCU8xdPeT0xscg4UES62Jml5xLCck0rDMwqRjci', 'ROLE_ADMIN', 'admin');